
services:
  moodle:
    image: ndcuongdevops/moodle-lms:latest 
    container_name: moodle_app_run 
    restart: unless-stopped
    ports:
      - "8000:80" 
    volumes:
      - moodledata_vol:/var/www/moodledata
    depends_on:
      - db
    networks:
      - moodle-net
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBHOST: db 

  db:
    image: postgres:15
    container_name: moodle_db_run
    restart: unless-stopped
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    volumes:
      - moodledb_vol:/var/lib/postgresql/data
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge

volumes:
  moodledata_vol:
  moodledb_vol: